services:
  plumber-api:
    build: .
    image: brunosilvestre00/plumber-cat-api
    command: Rscript main.R
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - cat-api

networks:
  cat-api:
    external: true
    name: cat-api